<?php

namespace Apps\Cores\Views\Layouts;

/* @var $this TwoColsLayout */

$this->setTitle('Danh mục động')
        ->setHeader('Danh mục động');
?>

<style>
    .alert{margin-bottom: 10px;}
    .layout > div > .content{overflow-y: auto;position: relative;box-sizing: border-box;}
    .layout > .col-xs-8 > .content{border-left: 1px solid #ccc;}
    .layout > .col-xs-8 > .content .actions{position: absolute;top: 0;left: 0;right: 0; height: 50px; line-height: 50px;border-bottom: 1px solid #ccc;padding: 0 10px;background: #eee;}
    .layout > .col-xs-8 > .content .actions input{width: 200px;display: inline-block;}
    .layout > .col-xs-8 > .content .items{position: absolute;top: 50px;bottom: 0;overflow-y: auto;}
    .table-items td{padding: 0 !important;}
    .table-items td input{display: block;border: none;width: 100%;box-sizing: border-box;outline: none;padding: 0 5px;height: 35px;background: transparent;}
</style>

<div class="alert alert-actions alert-success">
    <button type="button" class="btn btn-default"><i class="fa fa-plus"></i> Thêm danh mục</button>
</div>
<div class="row layout">
    <div class="col-xs-4">
        <div class="content">
            <table class="table table-hover">
                <tr>
                    <td>Danh mục ứng dụng</td>
                </tr>
                <tr class="info">
                    <td>Danh muc test</td>
                </tr>
                <tr>
                    <td>Danh mục ứng dụng</td>
                </tr>
                <tr>
                    <td>Danh mục ứng dụng</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-xs-8">
        <div class="content">
            <div class="actions">
                <input type="text" placeholder="Mã" class="form-control"/>
                <input type="text" placeholder="Tên" class="form-control"/>
                <button class="btn btn-default"><i class="fa fa-save"></i></button>
                <button class="btn btn-default"><i class="fa fa-trash"></i></button>
            </div>
            <div class="items">
                <table class="table table-bordered table-hover table-condensed table-items">
                    <thead>
                        <tr>
                            <th width="10%">STT</th>
                            <th width="30%">Mã đối tượng</th>
                            <th width="50%">Giá trị</th>
                            <th width="10%" class="center">Xóa</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach (range(1, 20) as $i): ?>
                            <tr>
                                <td><input type="text"/></td>
                                <td><input type="text"/></td>
                                <td><input type="text"/></td>
                                <td class="center"><button type="button" class="btn btn-default" ><i class="fa fa-remove"></i></button></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        $(window).resize(function () {
            var height = $(window).height() - $('.layout').offset().top - 5;
            console.log($('.layout > div > .content'));
            $('.layout > div > .content').each(function () {
                $(this).height(height);
            });
        }).trigger('resize');
    });
</script>