<?php

use Apps\Cores\Views\Layouts\DefaultLayout;
use Apps\Cores\Models\DepartmentEntity;

/* @var $this DefaultLayout */
/* @var $department DepartmentEntity */
/* @var $editDep DepartmentEntity */
$this->setTitle('Tài khoản')
        ->setSideMenuActive('user')
        ->addJs(array(
            $this->themeUrl() . '/components/DepartmentPicker/DepartmentPicker.js',
            $this->themeUrl() . '/js/views/userCtrl.js',
        ));
?>

<style>
    .tbl-row{height: 40px;position: relative;}
    table .fa-folder-open{color: #fbc02d;}
    table .fa-user{color: #ccc;}
    .tbl-type .fa{font-size: 1.5em;}
    table th{min-width: 50px;}
    table th:nth-child(5){width: 100%;}
    table th:last-child{min-width: 120px;}
    .parent-dep{position: relative;}
    .parent-dep > span{position: absolute;right: 10px;top:0; height: 34px; line-height: 34px;display: inline-block;font-size: 21px;}
    #editDep{background: white;cursor: pointer;}
    span.id{color: gray}
    #filter-name{width: 200px;}
    #user-tree .panel-body{min-height: 300px;}
</style>

<angular ng-cloak ng-controller="userCtrl">
    <div class="row">
        <div class="col-xs-12">
            <h1 class="page-header">Tài khoản</h1>
        </div>
    </div>

    <ol class="breadcrumb">
        <li>
            <div class="btn-group">
                <a href="javascript:;" ng-class="<?php echo "{'disabled': !depPk}" ?>" ng-click="goUp()"  class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Quay lại">
                    <i class="fa fa-arrow-left"></i>
                </a>
                <a href="#" ng-class="<?php echo "{'disabled': !depPk}" ?>" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Trở về gốc">
                    <i class="fa fa-home"></i>
                </a>
            </div>
        </li>
        <li ng-repeat="ancestor in department.ancestors">
            <a href="#/{{ancestor.pk}}">{{ancestor.depName}}</a>
        </li>
        <li class="active">{{department.depName}}</li>
    </ol>

    <div class="panel" id="user-tree">
        <div class="panel-body">
            <div>
                <div class="pull-left">
                    <!--buttons-->
                    <button class="btn btn-primary btn-labeled fa fa-user" ng-click="editUser()">
                        Thêm tài khoản
                    </button>
                    <button class="btn btn-success btn-labeled fa fa-folder-open" ng-click="editDep()">
                        Thêm đơn vị
                    </button>
                    <button type="button" class="btn btn-default btn-labeled fa fa-exchange" ng-disabled="!anythingChecked()" ng-click="move()">Chuyển tới</button>
                    <button type="button" class="btn btn-default btn-labeled fa fa-trash" ng-disabled="!anythingChecked()" ng-click="delete()">Xóa</button>
                    <!--end buttons-->
                </div>
                <div class="pull-right">
                    <input type="text" class="form-control"  id="filter-name" name="search" placeholder="tìm đơn vị, người dùng" ng-model="filter.search"/>
                </div>
                <div class="clearfix"></div>
            </div>

            <h4></h4>
            <table class="table table-record  table-striped table-hover" ng-show="department">
                <thead>
                    <tr>
                        <th class="center">
                            <label class="check">
                                <input type="checkbox" />
                                <before></before>
                                <after></after>
                            </label>
                        </th>
                        <th class="center">Loại</th>
                        <th></th>
                        <th>ID</th>
                        <th>Tên</th>
                        <th>Trạng thái</th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-if="department && !department.users.length && !department.deps.length">
                        <td colspan="6" class="center"><Br>Chưa có thư mục và tài khoản trong đơn vị.<br>&nbsp;</td>
                    </tr>
                    <tr ng-if="searchResult && !searchResult.users.length && !searchResult.departments.length">
                        <td colspan="6" class="center"><Br>Không tìm thấy kết quả nào.<br>&nbsp;</td>
                    </tr>

                    <tr ng-repeat="childDep in deps()" ng-class="<?php echo "{'stt-active': childDep.stt, 'stt-inactive': !childDep.stt}" ?>">
                        <td class="center ">
                            <div class="tbl-check">
                                <input type="checkbox" value="{{childDep.pk}}" ng-model="checkedDeps[childDep.pk]" />
                            </div>
                        </td>
                        <td class="tbl-type center">
                            <i class="fa fa-folder-open"></i>
                        </td>
                        <td class="tbl-actions center">
                            <div class="dropdown">
                                <a href="javascript:;" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bars"></i></a>
                                <ul class="dropdown-menu">
                                    <li><a href="javascript:;" ng-click="editDep(childDep)">Sửa</a></li>
                                    <li><a href="javascript:;" ng-click="deleteDep(childDep)">Xóa</a></li>
                                </ul>
                            </div>
                        </td>
                        <td><span class="id">{{childDep.pk}}</span></td>
                        <td class="tbl-text">
                            <a href="#/{{childDep.pk}}" class="btn-link">{{childDep.depName}}</a> 
                            <br>
                            Đơn vị/Phòng ban
                        </td>
                        <td>
                            <div ng-if="childDep.stt" class="label label-table label-success">Hoạt động</div>
                            <div ng-if="!childDep.stt" class="label label-table label-dark">Không hoạt động</div>
                        </td>
                    </tr>
                    <tr ng-repeat="user in users()" ng-class="<?php echo "{'stt-active': user.stt, 'stt-inactive': !user.stt}" ?>">
                        <td class="center">
                            <div class="tbl-check">
                                <input type="checkbox" value="{{user.pk}}" ng-model="checkedUsers[user.pk]" ng-disabled="user.isAdmin"/>
                            </div>
                        </td>
                        <td class="tbl-type center">
                            <i class="fa fa-user"></i>
                        </td>
                        <td class="tbl-actions center">
                            <div class="dropdown">
                                <a href="javascript:;" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bars"></i></a>
                                <ul class="dropdown-menu">
                                    <li><a href="javascript:;" ng-click="editUser(user)">Sửa</a></li>
                                    <li><a href="javascript:;" ng-click="copyUser(user)">Sao chép</a></li>
                                    <li><a href="javascript:;" ng-if="!user.isAdmin" ng-click="deleteUser(user)">Xóa</a></li>
                                </ul>
                            </div>
                        </td>
                        <td><span class="id">{{user.pk}}</span></td>
                        <td class="tbl-text">
                            <a href="javascript:;" class="btn-link" ng-click="editUser(user)">{{user.fullName}}</a>
                            <br>
                            {{user.jobTitle}}
                        </td>
                        <td>
                            <div ng-if="user.stt" class="label label-table label-success">Hoạt động</div>
                            <div ng-if="!user.stt" class="label label-table label-dark">Không hoạt động</div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div><!--panel body-->
    </div><!--panel-->



    <!--department form-->
    <?php require __DIR__ . '/editDep.phtml' ?>
    <!--user form-->
    <?php require __DIR__ . '/editUser.phtml' ?>

    <!--department picker-->
    <div ng-department-picker></div>
</angular>
